---
- name: Deploy the demo app to OpenShift
  hosts: all

  tasks:
    - name: login to the cluster
      shell: "oc login --token={{ ocp_token }} --server={{ ocp_server }}"

    - name: create the deployment
      shell: oc create -f deployment.yml
