---
- name: Deploy the demo app to OpenShift
  hosts: all

  - tasks:
      - name: login to the cluster
        shell: "oc login --token={{ ocp_token }} --server=https://c100-e.au-syd.containers.cloud.ibm.com:32653"

      - name: create the deployment
        shell: oc create -f deployment.yml
