---
- name: Deploy the demo app to OpenShift
  hosts: all

  collections:
    - community.kubernetes

  tasks:
    - name: create the deployment
      community.kubernetes.k8s:
        host: "{{ ocp_server }}"
        api_key: "{{ ocp_token }}"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            annotations:
              deployment.kubernetes.io/revision: "1"
            generation: 1
            labels:
              app: cybr-demo
            name: cybr-demo
            namespace: cyberark
          spec:
            progressDeadlineSeconds: 600
            replicas: 1
            revisionHistoryLimit: 10
            selector:
              matchLabels:
                deployment: cybr-demo
            strategy:
              rollingUpdate:
                maxSurge: 25%
                maxUnavailable: 25%
              type: RollingUpdate
            template:
              metadata:
                creationTimestamp: null
                labels:
                  deployment: cybr-demo
              spec:
                containers:
                - image: quay.io/smileyfritz/cybr-demo:v1.2
                  imagePullPolicy: IfNotPresent
                  name: cybr-demo
                  ports:
                  - containerPort: 8080
                    protocol: TCP
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                dnsPolicy: ClusterFirst
                restartPolicy: Always
                schedulerName: default-scheduler
                securityContext: {}
                terminationGracePeriodSeconds: 30
